# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: AssembyInfoReader@2
  inputs:
    searchPattern: '**\AssemblyInfo.cs'
    variablesPrefix: 'AI_'

- task: AssembyInfoReader@2
  inputs:
    searchPattern: '**\AssemblyVersionInfo.cs'
    variablesPrefix: 'AVI_'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'sumo300'
    scannerMode: 'MSBuild'
    projectKey: 'sumo300_seesharpship'
    projectName: 'seesharpship'
    projectVersion: $(AVI_AssemblyInfo.AssemblyVersion)

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'